### ISSUE TITLE
Toledo Javascript UCI in combination with Worse Chess

### ISSUE THREAD

**Issue by yellow-panther** [ecrucru/worse-chess#1]
Can you explain me how Toledo JavaScript UCI can be used together with Worse Chess, please?

I can run Toledo JS UCI alone on WinBoard 4.8.0 but not with the option "Worse Chess" on Windows 7 32-bit SP1.
Node JS 8.11.3 LTS x86  https://nodejs.org/en/, Worse Chess and ToledoChessJS-UCI are completely  installed here:

C:\Benutzer\NRL\Downloads\nodejs\ Is a batch-file or something else required with Notepad++?

**Comment by ecrucru** [comment]
Hello yellow-panther,

Toledo NanoChess cannot work with Worse Chess because it always provides a single move for a given position. There is nothing I can do to improve that situation.

So you must use another engine. I mainly tested with Stockfish and Komodo, and I don't know which compatible engine written in JavaScript you can use.

Regards

**Comment by yellow-panther** [comment]
It is possible to host a complete download package with e.g. SF 9 x64
popcnt.exe , your application and node.js for Windows x64
https://nodejs.org/en/ ?

Google Drive https://www.google.com/intl/fr_ALL/drive/ could be such an
option with enough memory place

All three applications are available into the folder
C:\\Benutzer\NRL\Downloads\nodejs\

For me it is not clear whether an extra Nodepad batch-file
C:\\Benutzer\NRL\Downloads\nodejs\stockfish_9_x64_popcnt.exe
is necessary.

WinBoard: http://www.open-aurec.com/wbforum/viewtopic.php?f=19&t=51528

2018-06-17 14:58 GMT+02:00 ecrucru <notifications@github.com>:

**Comment by ecrucru** [comment]
Hello @yellow-panther,

This little script is platform-independent. Making a package is a technical non-sense due to the diversity of computers that exist in the world (operating system, bitness, CPU architecture...). Basically, the chess players who can be interested in the script have a working chess environment already, but without the dependent NodeJS which setup is clean and easy.

The JS file for the players is available [for direct download](https://github.com/ecrucru/worse-chess/releases/). Follow the [README](https://github.com/ecrucru/worse-chess/blob/master/README.md) to define inside the script the real engine to be used (no need of an additional batch file). Then with PyChess, add the modified JS file to the list of engines, or for Win/XBoard, you should define something complex like that in the configuration file :
```
"Worse Chess" -fcp 'C:\path\node.exe "C:\path\worse-chess.js"' -fn "Worse Chess" -fUCI
```

Tell me if you need more information.

Regards
